### ISSUE TITLE
jekyll-scholar breaking build

### ISSUE THREAD

**Issue by rkurchin** [sbryngelson/academic-website-template#2]
Thank you so much for this beautiful template! I have my site all set up (based somewhat off of [your group's site](https://github.com/comp-physics/comp-physics.github.io) and it runs locally just fine, but the "vanilla" GH Pages deployment is breaking because it doesn't recognize the `bibliography` command, which seems to be because [jekyll-scholar isn't in GitHub's supported plugins](https://pages.github.com/versions/). I tried a bunch of solutions to this that I found in a number of places, but haven't quite gotten it working (the closest attempt did publish the site, but seemed to just be "raw" HTML (i.e. black text on a white background, so all the CSS was being ignored maybe?).

I'm really not an expert in this stuff, but it seems like you're possibly getting around this via something similar to the approach suggested in the first paragraph [here](https://github.com/inukshuk/jekyll-scholar#github-pages), but I infer this only from the presence of a `Rakefile` – what I can see on the Actions history on your group site suggests that Jekyll is in fact building the site, and that seems a lot easier, so if there's in fact some way to achieve that that I haven't figured out, that would be amazing.

Hope this all makes sense...thanks again!!

**Comment by rkurchin** [comment]
Sorry, I figured it out – I had to deploy with GitHub Pages rather than deploying from a branch. It works now! 🥳

**Comment by sbryngelson** [comment]
No problem @rkurchin -- I should add more info. for this in the readme!

**Comment by rkurchin** [comment]
BTW, feel free to add my group's page as another example if you like: https://acme-group-cmu.github.io/ACMEgroup/

**Comment by sbryngelson** [comment]
Good idea - done!
